# Permalinks
permalink: pretty

# Setup
title: FPBioimage
tagline: ''
description: ''
url: https://fpb.ceb.cam.ac.uk
baseurl: "/"
paginate_path: "posts/page:num"
markdown: kramdown

author:
  name: 'Marcus Fantham'
  url: https://laser.ceb.cam.ac.uk/directory/marcus-fantham

paginate: 5
